name: FastAPI Deployment for LongMemoire Chatbot

on:
  push:
    branches:
      - main
    paths:
      - 'workers/chatbots/LongMemoire/**'

jobs:
  deploy-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install -r workers/chatbots/LongMemoire/requirements.txt

    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Set Startup Command for Azure WebApp
      env:
        AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
      run: |
        az webapp config set --name LongMemoireChatbotApp --resource-group PitreWebpageResourceGroup --startup-file "uvicorn app:app --host 0.0.0.0 --port 8000"

    - name: Deploy FastAPI App to Azure WebApp
      env:
        AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
      run: |
        az webapp deployment source config --name LongMemoireChatbotApp --resource-group PitreWebpageResourceGroup --repo-url https://github.com/coldcanuk/pitre-webpage --branch main --manual-integration

    - name: Test FastAPI App
      run: |
        # Add PowerShell script to test the application using invoke-restmethod
        # Example: invoke-restmethod -Uri "https://longmemoirechatbotapp.azurewebsites.net/chat" -Method Post -Body '{"prompt": "test"}' -ContentType "application/json"