name: FastAPI Deployment for LongMemoire Chatbot

on:
  push:
    branches:
      - main
    paths:
      - 'workers/chatbots/LongMemoire/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Build and Push Docker Image
      run: |
        docker build -t longmemoirechatbotapp ./workers/chatbots/LongMemoire/
        docker tag longmemoirechatbotapp pitreinforegistry.azurecr.io/longmemoirechatbotapp
        az acr login --name pitreinforegistry
        docker push pitreinforegistry.azurecr.io/longmemoirechatbotapp

    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy FastAPI App using Docker Image
      run: |
        az webapp config container set --name LongMemoireChatbotApp --resource-group PitreWebpageResourceGroup --docker-custom-image-name pitreinforegistry.azurecr.io/longmemoirechatbotapp --docker-registry-server-url https://pitreinforegistry.azurecr.io

    - name: Test FastAPI App
      run: |
        # Add PowerShell script to test the application using invoke-restmethod
        # Example: invoke-restmethod -Uri "https://longmemoirechatbotapp.azurewebsites.net/chat" -Method Post -Body '{"prompt": "test"}' -ContentType "application/json"